### ISSUE TITLE
convert read text files to JSON

### ISSUE THREAD

**Issue by mlp6** [mlp6/ProstateSensitivityAnalysis#29]
I made a silly mistake early on in writing blindly formatted text files for the ARFI, MRI and histology reads... this is a bit of a mess now.  Should have used JSON to be much more explicit and less place-dependent on the reading / parsing (also would have made life a lot easier on the identification and characterization of lesions).  Think of writing a conversion script once Tyler finished P65 and P68.

**Comment by mlp6** [comment]
@tjg17 can you take a look at the HistologyLesions.json file in Patient10 on the json branch to see if you like that format and if it is complete?  are there other fields that we should be considering adding?  we can then do the same for the ARFI and MRI reads too... I'll write a converter for all of our *.txt files.

**Comment by tjg17** [comment]
Yep - I'll take a look now

**Comment by tjg17** [comment]
Mark,

For the Histology files, is the top line necessarily the index lesion? I
had thought the code went through and determined the index based on
Gleason/size, but it seems like the JSON file automatically assigns the top
line as the index lesion. Is this what the JSON script will do?

I had run into some troubles defining the top line as the index when
reading in the MRI text files - but have a workaround in place where I tag
the index region in the read_mri method before the mri_lesions method where
the index was previously defined in the original code. This did work for
always assigning the top line to the index region.

Will the JSON make the text files more readable in general?

Thanks!
-Tyler

**Comment by mlp6** [comment]
I think that the JSON approach will be more readable, but also more robust for explicitly defining the index lesion with a field for that information.  I am verifying what the true index lesions are in the histology to make sure this is done correctly.

**Comment by tjg17** [comment]
Sounds good - I also was wondering if we had Extracapsular extension (ECE)
information available for the Histology lesions or by Histology case. MRI
calls included whether Raj thought ECE was present so this would be ripe
for an ECE analysis if so.

**Comment by tjg17** [comment]
Following up, I think the ECE information is on the Path Reports, but Path
Reports are not on /luscinia for all of the cases.

**Comment by tjg17** [comment]
Mark,

Ali has the ADC images on a disk but there is still some lingering PHI on
them. Do you know when you would be available to get the PHI off the data
before moving to /luscinia?

Thanks,
-Tyler

**Comment by mlp6** [comment]
We can create a field for ECE info for the MRI JSON files, and it can be missing for cases that do not have this information.  Check out the JSON converter that I generated for histology (now merged into master): ```convert_histology_txt_json.py```.  I will be doing the same for ARFI; do you want to tackle one for MRI populated with the fields that you want?

**Comment by tjg17** [comment]
All of the MRI tumor calls have whether ECE is present for each lesion -
this information is also in the Path Reports for all the cases but not all
of the Path Reports are on /luscinia so the incomplete information would
all be on Histology.  With the new JSON files, will the methods to read the
lesion information in also be changing?

Thanks,
-Tyler

**Comment by tjg17** [comment]
Mark,

I am still unsure of the advantage in switching to the JSON files for the
MRI tumor calls. I updated the methods in the MRAnalysis class such that
the top line of the text file is always read in as the index lesion - is
there another advantage to the JSON appraoch besides explicitly defining
the index lesion in the text file rather than after loading the text file
in to the Sensitivity analysis scripts?

The MRAnalysis class also already loads in the information for 'gleason',
'diameter', and 'extracap' as attributes for each lesion in addition to the
location and IOS information.

Thanks,
-Tyler

**Comment by mlp6** [comment]
Yep - we'll be handing a lot of these data off to Kitware, and our assumptions such as "first line is the index lesion" will be easy to loose in the handoff, and they might be adding more fields that we'll need to define.  We'll be able to use your code to read and interpret the files to generate the JSON files, so no code is wasted in this process, and it promotes methods in our analysis classes that are operational, not just defining things, which the JSON files should be doing.

**Comment by tjg17** [comment]
Gotcha - makes a lot more sense now with the added collaboration from
Kitware. I'll get to work on the MRI JSON txt converter this afternoon. I
also have some questions about the Histology tumor calls in P86 but it
would probably be best to look over in person - will you be available to
discuss tomorrow between 10-11:30am or after 3pm?

Thanks!
-Tyler

**Comment by mlp6** [comment]
10:00 works for me!

I am slogging through updating lesion_analysis.py to process the JSON input (nothing major different, but some small tweaks, hopefully all of which will be inhereted "behind the scenes" for your MRI class).  Hopefully this will be done tonight and we can merge everything in tomorrow!
