### ISSUE TITLE
JSON reader adding extra letters

### ISSUE THREAD

**Issue by tjg17** [mlp6/ProstateSensitivityAnalysis#43]
Bug with extra "u" in defining region using lesion_analysis class - also happens for histology information

>>>from lesion_analysis import LesionAnalysis
>>> P59 = LesionAnalysis(59)
>>> P59.arfi['index']['region']
u'11p'

**Comment by tjg17** [comment]
This seems to be an issue with json.load(f) command. Also tried json.loads(), json.dump(), and json(dumps() but all methods still result in extra u's in loaded information

**Comment by mlp6** [comment]
Not an error!  The 'u' shows up when printing the dictionary to indicate that the text is in Unicode format... but it should not affect using the strings, testing against them, etc.

**Comment by tjg17** [comment]
Thanks!
